### ISSUE TITLE
Installs EPEL 6 RPM on EPEL 5

### ISSUE THREAD

**Issue by mpdehaan** [bennojoy/redis#4]
There currently appears to be a glitch in the role where this will attempt to install the EPEL 6 RPM in EL 5, note the date of the review as this may have since been fixed, but it would be just as simple to remove EL 5 from the list of supported platforms and re-import the role if time is short.

I can then update my review on galaxy.ansibleworks

**Comment by bennojoy** [comment]
Thanks Michael,

Will update the metadata.

**Comment by bennojoy** [comment]
Fixed
